export const seedArtists = [
  {
    id: "artist-dj-op-dot",
    name: "DJ Op Dot",
    image: "/assets/Djopdot.jpg",
    role: "DJ, Hype Curator & Crowd Controller",
    bio: "Built for late-night sets and high-energy turnups, DJ Op Dot brings club pressure, street rhythm, and crowd command into one signature experience.",
    location: "Lagos, Nigeria",
    spotlight: "Festival-ready mixes, club edits, and performance-driven branding.",
    socials: {
      instagram: "",
      tiktok: "",
      youtube: "",
    },
    featuredOnHome: true,
  },
  {
    id: "artist-pearl",
    name: "Pearl",
    image: "/assets/Pearl.jpg",
    role: "Singer, Songwriter & Melodic Storyteller",
    bio: "Pearl blends soft confidence with sharp songwriting, shaping records that feel intimate, feminine, and instantly memorable.",
    location: "Abuja, Nigeria",
    spotlight: "Emotion-led vocals, crossover-ready hooks, and visual storytelling.",
    socials: {
      instagram: "",
      tiktok: "",
      youtube: "",
    },
    featuredOnHome: true,
  },
  {
    id: "artist-tekunbi",
    name: "Tekunbi",
    image: "/assets/Tekunbi.jpg",
    role: "Afropop Artist & Hook Specialist",
    bio: "Tekunbi delivers clean melodies, conversational lyrics, and replay value that sits comfortably between street-pop energy and polished radio appeal.",
    location: "Lagos, Nigeria",
    spotlight: "Catchy toplines, versatile collaborations, and commercial-ready singles.",
    socials: {
      instagram: "",
      tiktok: "",
      youtube: "",
    },
    featuredOnHome: true,
  },
  {
    id: "artist-wandey",
    name: "Wandey",
    image: "/assets/Wandey.jpg",
    role: "Street Pop Artist & Performer",
    bio: "Wandey brings bounce, charisma, and a direct connection to the street, with records designed to move fast from speakers to social feeds.",
    location: "Ibadan, Nigeria",
    spotlight: "Performance clips, energetic singles, and culture-first rollout ideas.",
    socials: {
      instagram: "",
      tiktok: "",
      youtube: "",
    },
    featuredOnHome: false,
  },
];

export const seedReleases = [
  {
    id: "release-night-shift",
    slug: "night-shift",
    title: "Night Shift",
    artistId: "artist-dj-op-dot",
    artistName: "DJ Op Dot",
    type: "Live DJ Set",
    coverImage: "/assets/Djopdot.jpg",
    summary: "A high-pressure late-night set built for packed rooms and restless speakers.",
    body: "Night Shift captures DJ Op Dot in full command mode: tight transitions, crowd-first pacing, and the kind of energy that carries from the first blend to the final cut. It is designed as both a release and a statement about where the Cityplug sound is headed.",
    releaseDate: "2026-04-25",
    streamingUrl: "",
    featuredOnHome: true,
  },
  {
    id: "release-soft-fire",
    slug: "soft-fire",
    title: "Soft Fire",
    artistId: "artist-pearl",
    artistName: "Pearl",
    type: "Single",
    coverImage: "/assets/Pearl.jpg",
    summary: "A melodic release balancing intimacy, confidence, and replay value.",
    body: "Soft Fire leans into Pearl's storytelling strength and her ability to make a record feel personal without losing commercial appeal. The release page is ready for rollout notes, lyrics, streaming links, and campaign updates.",
    releaseDate: "2026-04-19",
    streamingUrl: "",
    featuredOnHome: true,
  },
  {
    id: "release-outside-energy",
    slug: "outside-energy",
    title: "Outside Energy",
    artistId: "artist-tekunbi",
    artistName: "Tekunbi",
    type: "EP Focus Track",
    coverImage: "/assets/Tekunbi.jpg",
    summary: "An upbeat release positioned for fast pickup across radio, socials, and live shows.",
    body: "Outside Energy is built around clean melodies and immediate hooks. This page can carry the release story, embedded links, promo copy, and every update the admin wants to surface around the campaign.",
    releaseDate: "2026-04-10",
    streamingUrl: "",
    featuredOnHome: true,
  },
];
